### PR TITLE
added browser tests with webpack

### PR DESCRIPTION
**Pull request by qballer**
I've added webpack and made sure test passes in the browser.

### CODE REVIEW

**Comment by Schoonology** [comment]
Hey, @qballer, thanks for the patch! :wave: 

Can you go into a little more detail around the issues you've solved, or the philosophy around the change? I'm sorry - it caught me a little off guard, and I want to make sure I understand.

**Comment by qballer** [comment]
Hey @Schoonology  
I was trying to test if this will also perform the guard in the browser.  running the test failed because you can't return outside a function. 

 npm start my version and go to http://localhost:8080/webpack-dev-server, click the link next to webtest Browser test :)

**Comment by qballer** [comment]
Any news ?

**Comment by Schoonology** [comment]
I haven't had time to unpack the changes, but my general impression is that there is a lot of unrelated change.

**Comment by Schoonology** [comment]
I'd really like to support the same features, but I'd like to find a minimal update to do so. :smile:

**Comment by qballer** [comment]
no problem, do you want to narrow it down? 
Take it to a spin.

**Comment by Schoonology** [comment]
@qballer - I pushed a branch, `browser-tests`, that should address your problem. It uses Browserify in lieu of Webpack, but the outcome is the same: the tests are run against a headless browser, PhantomJS, and the errant `return` statement you addressed has been removed.

Does this solution work for you?

**Comment by qballer** [comment]
looks good

**Pull request closed without merging**
